package app

import (
	"github.com/gin-gonic/gin"
	"mediguide/internal/handlers"
	"mediguide/internal/middleware"
)

func registerClinicalContentRoutes(protected *gin.RouterGroup, guidelineContentH handlers.GuidelineContentHandler, diseaseH handlers.DiseaseHandler, contentDiseaseH handlers.ContentDiseaseHandler, contentHubH handlers.ContentHubHandler, emergencyProtocolH handlers.EmergencyProtocolHandler, contentReferenceH handlers.ContentReferenceHandler) {
	protected.GET("/medical-guidelines", middleware.RequirePermission("guideline.read"), guidelineContentH.ListMedicalGuidelines)
	protected.GET("/medical-guidelines/:id", middleware.RequirePermission("guideline.read"), guidelineContentH.GetMedicalGuideline)
	protected.POST("/medical-guidelines", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateMedicalGuideline)
	protected.PATCH("/medical-guidelines/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateMedicalGuideline)
	protected.DELETE("/medical-guidelines/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteMedicalGuideline)
	protected.GET("/guideline-categories", middleware.RequirePermission("guideline.read"), guidelineContentH.ListCategories)
	protected.GET("/guideline-categories/:id", middleware.RequirePermission("guideline.read"), guidelineContentH.GetCategory)
	protected.POST("/guideline-categories", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateCategory)
	protected.PATCH("/guideline-categories/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateCategory)
	protected.DELETE("/guideline-categories/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteCategory)
	// Document kinds are shared: outbreak editors read them to classify outbreak documents.
	protected.GET("/document-kinds", middleware.RequireAnyPermission("guideline.read", "outbreak.read"), guidelineContentH.ListDocumentKinds)
	protected.GET("/document-kinds/:id", middleware.RequireAnyPermission("guideline.read", "outbreak.read"), guidelineContentH.GetDocumentKind)
	protected.POST("/document-kinds", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateDocumentKind)
	protected.PATCH("/document-kinds/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateDocumentKind)
	protected.DELETE("/document-kinds/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteDocumentKind)
	protected.GET("/diseases", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.List)
	protected.GET("/diseases/hierarchy", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.Hierarchy)
	protected.GET("/diseases/migration-report", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.MigrationReport)
	protected.POST("/diseases/migration-report/refresh", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.RefreshMigrationReport)
	protected.GET("/diseases/:id", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.Get)
	protected.GET("/diseases/:id/aliases", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.ListAliases)
	protected.PUT("/diseases/:id/aliases", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.ReplaceAliases)
	protected.GET("/diseases/:id/codes", middleware.RequireAnyPermission("disease.taxonomy.read", "disease.taxonomy.manage"), diseaseH.ListCodes)
	protected.PUT("/diseases/:id/codes", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.ReplaceCodes)
	protected.POST("/diseases", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.Create)
	protected.PATCH("/diseases/:id", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.Update)
	protected.DELETE("/diseases/:id", middleware.RequirePermission("disease.taxonomy.manage"), diseaseH.Archive)
	protected.GET("/content-disease-assignments", middleware.RequireAnyPermission("disease.assignment.read", "disease.assignment.manage"), contentDiseaseH.List)
	protected.POST("/content-disease-assignments", middleware.RequirePermission("disease.assignment.manage"), contentDiseaseH.Create)
	protected.PUT("/content-disease-assignments/replace", middleware.RequirePermission("disease.assignment.manage"), contentDiseaseH.Replace)
	protected.DELETE("/content-disease-assignments/:id", middleware.RequirePermission("disease.assignment.manage"), contentDiseaseH.Delete)
	protected.GET("/content-hubs", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.List)
	protected.GET("/content-hubs/:id", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.Get)
	protected.GET("/content-hubs/:id/preview", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.Preview)
	protected.GET("/content-hubs/:id/diseases", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.ListDiseases)
	protected.PUT("/content-hubs/:id/diseases", middleware.RequirePermission("content_hub.manage"), contentHubH.ReplaceDiseases)
	protected.GET("/content-hubs/:id/workspace", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.Workspace)
	protected.GET("/content-hubs/:id/audit", middleware.RequireAnyPermission("content_hub.read", "content_hub.manage"), contentHubH.Audit)
	protected.GET("/content-hub-resources", middleware.RequireAnyPermission("content_pillar.read", "content_pillar.manage"), contentHubH.SearchResources)
	protected.POST("/outbreaks/:id/content-hub", middleware.RequirePermission("content_hub.manage"), contentHubH.ConfigureOutbreak)
	protected.POST("/content-hubs", middleware.RequirePermission("content_hub.manage"), contentHubH.Create)
	protected.PATCH("/content-hubs/:id", middleware.RequirePermission("content_hub.manage"), contentHubH.Update)
	protected.DELETE("/content-hubs/:id", middleware.RequirePermission("content_hub.manage"), contentHubH.Delete)
	protected.POST("/content-hubs/:id/publish", middleware.RequirePermission("content_hub.publish"), contentHubH.Publish)
	protected.POST("/content-hubs/:id/archive", middleware.RequirePermission("content_hub.archive"), contentHubH.Archive)
	protected.GET("/content-hubs/:id/pillars", middleware.RequireAnyPermission("content_pillar.read", "content_pillar.manage"), contentHubH.ListPillars)
	protected.POST("/content-hubs/:id/pillars", middleware.RequirePermission("content_pillar.manage"), contentHubH.CreatePillar)
	protected.PATCH("/content-hubs/:id/pillars/:pillarId", middleware.RequirePermission("content_pillar.manage"), contentHubH.UpdatePillar)
	protected.DELETE("/content-hubs/:id/pillars/:pillarId", middleware.RequirePermission("content_pillar.manage"), contentHubH.DeletePillar)
	protected.PUT("/content-hubs/:id/pillars/reorder", middleware.RequirePermission("content_pillar.manage"), contentHubH.ReorderPillars)
	protected.GET("/content-hubs/:id/pillars/:pillarId/items", middleware.RequireAnyPermission("content_pillar.read", "content_pillar.manage"), contentHubH.ListPillarItems)
	protected.POST("/content-hubs/:id/pillars/:pillarId/items", middleware.RequirePermission("content_pillar.manage"), contentHubH.CreatePillarItem)
	protected.PATCH("/content-hubs/:id/pillars/:pillarId/items/:itemId", middleware.RequirePermission("content_pillar.manage"), contentHubH.UpdatePillarItem)
	protected.DELETE("/content-hubs/:id/pillars/:pillarId/items/:itemId", middleware.RequirePermission("content_pillar.manage"), contentHubH.DeletePillarItem)
	protected.PUT("/content-hubs/:id/pillars/:pillarId/items/reorder", middleware.RequirePermission("content_pillar.manage"), contentHubH.ReorderPillarItems)
	protected.GET("/content-hub-templates", middleware.RequireAnyPermission("content_hub.template.read", "content_hub.template.manage"), contentHubH.ListTemplates)
	protected.GET("/content-hub-templates/:id", middleware.RequireAnyPermission("content_hub.template.read", "content_hub.template.manage"), contentHubH.GetTemplate)
	protected.POST("/content-hubs/:id/apply-template", middleware.RequirePermission("content_hub.template.manage"), contentHubH.ApplyTemplate)
	protected.GET("/guideline-tags", middleware.RequirePermission("guideline.read"), guidelineContentH.ListTags)
	protected.GET("/guideline-tags/:id", middleware.RequirePermission("guideline.read"), guidelineContentH.GetTag)
	protected.POST("/guideline-tags", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateTag)
	protected.PATCH("/guideline-tags/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateTag)
	protected.DELETE("/guideline-tags/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteTag)
	protected.GET("/guideline-index", middleware.RequirePermission("guideline.read"), guidelineContentH.ListIndex)
	protected.GET("/guideline-index/:id", middleware.RequirePermission("guideline.read"), guidelineContentH.GetIndex)
	protected.GET("/guideline-index/:id/children", middleware.RequirePermission("guideline.read"), guidelineContentH.IndexChildren)
	protected.POST("/guideline-index", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateIndex)
	protected.PATCH("/guideline-index/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateIndex)
	protected.DELETE("/guideline-index/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteIndex)
	protected.GET("/abbreviations", middleware.RequirePermission("guideline.read"), guidelineContentH.ListAbbreviations)
	protected.GET("/abbreviations/:id", middleware.RequirePermission("guideline.read"), guidelineContentH.GetAbbreviation)
	protected.POST("/abbreviations", middleware.RequirePermission("guideline.write"), guidelineContentH.CreateAbbreviation)
	protected.PATCH("/abbreviations/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.UpdateAbbreviation)
	protected.DELETE("/abbreviations/:id", middleware.RequirePermission("guideline.write"), guidelineContentH.DeleteAbbreviation)
	protected.GET("/emergency-protocols", middleware.RequireAnyPermission("protocol.read", "guideline.read"), emergencyProtocolH.List)
	protected.GET("/emergency-protocols/:id", middleware.RequireAnyPermission("protocol.read", "guideline.read"), emergencyProtocolH.Get)
	protected.POST("/emergency-protocols", middleware.RequireAnyPermission("protocol.write", "guideline.write"), emergencyProtocolH.Create)
	protected.PATCH("/emergency-protocols/:id", middleware.RequireAnyPermission("protocol.write", "guideline.write"), emergencyProtocolH.Update)
	protected.DELETE("/emergency-protocols/:id", middleware.RequireAnyPermission("protocol.write", "guideline.write"), emergencyProtocolH.Delete)
	protected.GET("/pages", contentReferenceH.ListPages)
	protected.GET("/pages/key/:key", contentReferenceH.GetPageByKey)
	protected.GET("/pages/:id", contentReferenceH.GetPage)
	protected.POST("/pages", middleware.RequireAnyPermission("content.write", "guideline.write"), contentReferenceH.CreatePage)
	protected.PATCH("/pages/:id", middleware.RequireAnyPermission("content.write", "guideline.write"), contentReferenceH.UpdatePage)
	protected.DELETE("/pages/:id", middleware.RequireAnyPermission("content.write", "guideline.write"), contentReferenceH.DeletePage)
	protected.GET("/ministry-directory", contentReferenceH.ListDirectory)
	protected.GET("/ministry-directory/:id", contentReferenceH.GetDirectory)
	protected.POST("/ministry-directory", middleware.RequireAnyPermission("content.write", "facility.write"), contentReferenceH.CreateDirectory)
	protected.PATCH("/ministry-directory/:id", middleware.RequireAnyPermission("content.write", "facility.write"), contentReferenceH.UpdateDirectory)
	protected.DELETE("/ministry-directory/:id", middleware.RequireAnyPermission("content.write", "facility.write"), contentReferenceH.DeleteDirectory)
}
