package app

import (
	"github.com/gin-gonic/gin"
	"mediguide/internal/handlers"
	"mediguide/internal/middleware"
)

func registerOutbreakRoutes(protected *gin.RouterGroup, outbreakAdminH handlers.OutbreakAdminHandler) {
	protected.GET("/outbreaks", middleware.RequirePermission("outbreak.read"), outbreakAdminH.ListOutbreaks)
	protected.POST("/outbreaks", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CreateOutbreak)
	protected.GET("/outbreaks/:id", middleware.RequirePermission("outbreak.read"), outbreakAdminH.GetOutbreak)
	protected.PATCH("/outbreaks/:id", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UpdateOutbreak)
	protected.PATCH("/outbreaks/:id/metrics", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UpdateMetrics)
	protected.DELETE("/outbreaks/:id", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.DeleteOutbreak)
	protected.POST("/outbreaks/:id/submit", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.TransitionOutbreak("submit"))
	protected.POST("/outbreaks/:id/approve", middleware.RequirePermission("outbreak.review"), outbreakAdminH.TransitionOutbreak("approve"))
	protected.POST("/outbreaks/:id/publish", middleware.RequirePermission("outbreak.publish"), outbreakAdminH.TransitionOutbreak("publish"))
	protected.POST("/outbreaks/:id/withdraw", middleware.RequirePermission("outbreak.withdraw"), outbreakAdminH.TransitionOutbreak("withdraw"))
	protected.POST("/outbreaks/:id/update-status", middleware.RequirePermission("outbreak.publish"), outbreakAdminH.TransitionOutbreak("update_status"))
	protected.POST("/outbreaks/:id/correct", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CorrectOutbreak)
	protected.GET("/outbreaks/:id/audit", middleware.RequirePermission("outbreak.read"), outbreakAdminH.ListAudit("outbreak"))
	protected.POST("/outbreaks/:id/review-comments", middleware.RequirePermission("outbreak.review"), outbreakAdminH.AddReviewComment("outbreak"))
	protected.GET("/outbreaks/:id/updates", middleware.RequirePermission("outbreak.read"), outbreakAdminH.ListUpdates)
	protected.POST("/outbreaks/:id/updates", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CreateUpdate)
	protected.GET("/outbreaks/:id/updates/:updateId", middleware.RequirePermission("outbreak.read"), outbreakAdminH.GetUpdate)
	protected.PATCH("/outbreaks/:id/updates/:updateId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UpdateUpdate)
	protected.DELETE("/outbreaks/:id/updates/:updateId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.DeleteUpdate)
	protected.POST("/outbreaks/:id/updates/:updateId/submit", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.TransitionUpdate("submit"))
	protected.POST("/outbreaks/:id/updates/:updateId/approve", middleware.RequirePermission("outbreak.review"), outbreakAdminH.TransitionUpdate("approve"))
	protected.POST("/outbreaks/:id/updates/:updateId/publish", middleware.RequirePermission("outbreak.publish"), outbreakAdminH.TransitionUpdate("publish"))
	protected.POST("/outbreaks/:id/updates/:updateId/withdraw", middleware.RequirePermission("outbreak.withdraw"), outbreakAdminH.TransitionUpdate("withdraw"))
	protected.POST("/outbreaks/:id/updates/:updateId/correct", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CorrectUpdate)
	protected.GET("/outbreaks/:id/resources", middleware.RequirePermission("outbreak.read"), outbreakAdminH.ListResources)
	protected.POST("/outbreaks/:id/resources", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CreateResource)
	protected.GET("/outbreaks/:id/resources/:resourceId", middleware.RequirePermission("outbreak.read"), outbreakAdminH.GetResource)
	protected.PATCH("/outbreaks/:id/resources/:resourceId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UpdateResource)
	protected.DELETE("/outbreaks/:id/resources/:resourceId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.DeleteResource)
	protected.POST("/outbreaks/:id/resources/:resourceId/submit", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.TransitionResource("submit"))
	protected.POST("/outbreaks/:id/resources/:resourceId/approve", middleware.RequirePermission("outbreak.review"), outbreakAdminH.TransitionResource("approve"))
	protected.POST("/outbreaks/:id/resources/:resourceId/publish", middleware.RequirePermission("outbreak.publish"), outbreakAdminH.TransitionResource("publish"))
	protected.POST("/outbreaks/:id/resources/:resourceId/withdraw", middleware.RequirePermission("outbreak.withdraw"), outbreakAdminH.TransitionResource("withdraw"))
	protected.POST("/outbreaks/:id/resources/:resourceId/correct", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CorrectResource)
	protected.GET("/outbreaks/:id/documents", middleware.RequirePermission("outbreak.read"), outbreakAdminH.ListDocuments)
	protected.POST("/outbreaks/:id/documents", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CreateDocument)
	protected.GET("/outbreaks/:id/documents/:documentId", middleware.RequirePermission("outbreak.read"), outbreakAdminH.GetDocument)
	protected.PATCH("/outbreaks/:id/documents/:documentId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UpdateDocument)
	protected.DELETE("/outbreaks/:id/documents/:documentId", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.DeleteDocument)
	protected.PUT("/outbreaks/:id/documents/:documentId/file", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.UploadDocument)
	protected.GET("/outbreaks/:id/documents/:documentId/content", middleware.RequirePermission("outbreak.read"), outbreakAdminH.AdminDocumentContent)
	protected.GET("/outbreaks/:id/documents/:documentId/search-preview", middleware.RequirePermission("outbreak.read"), outbreakAdminH.DocumentSearchPreview)
	protected.POST("/outbreaks/:id/documents/:documentId/reprocess", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.ReprocessDocument)
	protected.GET("/outbreaks/:id/documents/:documentId/versions", middleware.RequirePermission("outbreak.read"), outbreakAdminH.DocumentVersions)
	protected.GET("/outbreaks/:id/documents/:documentId/audit", middleware.RequirePermission("outbreak.read"), outbreakAdminH.DocumentAudit)
	protected.POST("/outbreaks/:id/documents/:documentId/review-comments", middleware.RequirePermission("outbreak.review"), outbreakAdminH.AddDocumentReviewComment)
	protected.POST("/outbreaks/:id/documents/:documentId/submit", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.TransitionDocument("submit"))
	protected.POST("/outbreaks/:id/documents/:documentId/approve", middleware.RequirePermission("outbreak.review"), outbreakAdminH.TransitionDocument("approve"))
	protected.POST("/outbreaks/:id/documents/:documentId/publish", middleware.RequirePermission("outbreak.publish"), outbreakAdminH.TransitionDocument("publish"))
	protected.POST("/outbreaks/:id/documents/:documentId/withdraw", middleware.RequirePermission("outbreak.withdraw"), outbreakAdminH.TransitionDocument("withdraw"))
	protected.POST("/outbreaks/:id/documents/:documentId/corrections", middleware.RequirePermission("outbreak.manage"), outbreakAdminH.CorrectDocument)
	protected.GET("/situation-reports", middleware.RequirePermission("situation_report.read"), outbreakAdminH.ListReports)
	protected.POST("/situation-reports", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.CreateReport)
	protected.GET("/situation-reports/:id", middleware.RequirePermission("situation_report.read"), outbreakAdminH.GetReport)
	protected.PATCH("/situation-reports/:id", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.UpdateReport)
	protected.DELETE("/situation-reports/:id", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.DeleteReport)
	protected.POST("/situation-reports/:id/submit", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.TransitionReport("submit"))
	protected.POST("/situation-reports/:id/approve", middleware.RequirePermission("situation_report.review"), outbreakAdminH.TransitionReport("approve"))
	protected.POST("/situation-reports/:id/publish", middleware.RequirePermission("situation_report.publish"), outbreakAdminH.TransitionReport("publish"))
	protected.POST("/situation-reports/:id/withdraw", middleware.RequirePermission("situation_report.withdraw"), outbreakAdminH.TransitionReport("withdraw"))
	protected.POST("/situation-reports/:id/correct", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.CorrectReport)
	protected.POST("/situation-reports/:id/asset", middleware.RequirePermission("situation_report.manage"), outbreakAdminH.UploadReportAsset)
	protected.GET("/situation-reports/:id/audit", middleware.RequirePermission("situation_report.read"), outbreakAdminH.ListAudit("situation_report"))
	protected.POST("/situation-reports/:id/review-comments", middleware.RequirePermission("situation_report.review"), outbreakAdminH.AddReviewComment("situation_report"))
}
